client_config_backend: file
client_config:
  client_id: 592651808807-uglmqam5e2ai3ccstg0ovgim4lsocokh.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive

